//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TilausDB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sivustolla_vierailijat
    {
        public Nullable<int> Vierailijat { get; set; }
        public int Vuosi { get; set; }
    
        public virtual Myynnit Myynnit { get; set; }
    }
}
